### ISSUE TITLE
File error

### ISSUE THREAD

**Issue by Dazai1947** [davabase/whisper_real_time#11]
Error:

Traceback (most recent call last):
  File "C:\Users\MSI\PycharmProjects\Jarvis\test_2.py", line 131, in <module>
    main()
  File "C:\Users\MSI\PycharmProjects\Jarvis\test_2.py", line 103, in main
    result = audio_model.transcribe(temp_file, fp16=torch.cuda.is_available())
  File "C:\Users\MSI\PycharmProjects\Jarvis\venv\lib\site-packages\whisper\transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
  File "C:\Users\MSI\PycharmProjects\Jarvis\venv\lib\site-packages\whisper\audio.py", line 130, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\MSI\PycharmProjects\Jarvis\venv\lib\site-packages\whisper\audio.py", line 46, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\MSI\PycharmProjects\Jarvis\venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\MSI\PycharmProjects\Jarvis\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Не удается найти указанный файл

Process finished with exit code 1

I get this error, I do not know what the reason is. The error comes out after the inscription "Model Loaded". So I think the error is in the second half of the code. I used the original code, just changed the model to a small one. Can you help me?

**Comment by Kakcalu13** [comment]
did you find the solution? I face the same issue
