### ISSUE TITLE
Getting this error when running

### ISSUE THREAD

**Issue by ibrahim91015** [davabase/whisper_real_time#12]
getting this error when running the script
```C:\Users\ibrah\Desktop> py demo.py
Model loaded.

Traceback (most recent call last):
  File "C:\Users\ibrah\Desktop\demo.py", line 152, in <module>
    main()
  File "C:\Users\ibrah\Desktop\demo.py", line 124, in main
    result = audio_model.transcribe(temp_file, fp16=torch.cuda.is_available())
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\audio.py", line 130, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper\audio.py", line 46, in load_audio
    ffmpeg.input(file, threads=0)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified```

**Comment by davabase** [comment]
You must have ffmpeg installed on your machine.

You can install it with Chocolatey like so:
```
# using Chocolatey (https://chocolatey.org/)
choco install ffmpeg
```
or with Scoop:
```
# using Scoop (https://scoop.sh/)
scoop install ffmpeg
```
or from the ffmpeg website: https://ffmpeg.org/

**Comment by ibrahim91015** [comment]
Works! Thanks!
Using quite a bit of CPU, anyway to have it use the gpu instead?

**Comment by davabase** [comment]
To make sure you are using the CUDAversion of pytorch you can do a `pip uninstall torch` and then install the CUDA version of pytorch with:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
```
from the [pytorch website](https://pytorch.org/get-started/locally/).
If you installed via the `requirements.txt` this should already be true.
Make sure `torch.cuda.is_available()` is `True` in your environment.
Whisper should detect your GPU and use it automatically in that case, if it's not you can changing [line 69](https://github.com/davabase/whisper_real_time/blob/master/transcribe_demo.py#L69) to:
```
audio_model = whisper.load_model(model, device="cuda")
```
to force it to use the GPU.

**Comment by ibrahim91015** [comment]
did that, now im gettin this error: 
```
Traceback (most recent call last):
  File "C:\Users\ibrah\Desktop\whisper_real_time-master\transcribe_demo.py", line 152, in <module>
    main()
  File "C:\Users\ibrah\Desktop\whisper_real_time-master\transcribe_demo.py", line 69, in main
    audio_model = whisper.load_model(model, device="cuda")
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\whisper\__init__.py", line 144, in load_model
    checkpoint = torch.load(fp, map_location=device)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 1083, in restore_location
    return default_restore_location(storage, map_location)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by davabase** [comment]
```
torch.cuda.is_available() is False
```
Unfortunately it looks like you do not have a CUDA compatible GPU.

**Comment by ibrahim91015** [comment]
that's weird
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/65432743/234065935-eca5c138-1173-4cc5-84b2-c115419dc6cc.png">

**Comment by joacripto** [comment]
Hi!, I have the same problem than @ibrahim91015. The script runs well on CPU but I force the use of the GPU, I get the same `torch.cuda.is_available() is False` error, but: 
`❯ nvidia-smi
Sat Aug 26 18:20:07 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 532.09                 Driver Version: 532.09       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4080 L...  WDDM | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P8                8W /  N/A|    382MiB / 12282MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+`
So, any ideas?

Thak you so much
