### ISSUE TITLE
getting this error for memory allocation. what to do? is there any parameter I have to add?

### ISSUE THREAD

**Issue by durgeshhere** [davabase/whisper_real_time#19]
Traceback (most recent call last):
  File "c:\Users\laugh\OneDrive\Documents\GitHub\Dobby\base2.py", line 152, in <module>
    main()
  File "c:\Users\laugh\OneDrive\Documents\GitHub\Dobby\base2.py", line 69, in main     
    audio_model = whisper.load_model(model)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\whisper\__init__.py", line 154, in load_model
    return model.to(device)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1149, in to
    return self._apply(convert)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 801, in _apply
    module._apply(fn)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 801, in _apply
    module._apply(fn)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 801, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 824, in _apply
    param_applied = fn(param)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1147, in convert
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB. GPU 0 has a total capacty of 4.00 GiB of which 0 bytes is free. Of the allocated memory 3.44 GiB is allocated by PyTorch, 
and 15.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
PS C:\Users\laugh\OneDrive\Documents\GitHub\Dobby> & C:/Users/laugh/AppData/Local/Programs/Python/Python39/python.exe c:/Users/laugh/OneDrive/Documents/GitHub/Dobby/base2.py
Traceback (most recent call last):
  File "c:\Users\laugh\OneDrive\Documents\GitHub\Dobby\base2.py", line 152, in <module>
    main()
  File "c:\Users\laugh\OneDrive\Documents\GitHub\Dobby\base2.py", line 69, in main
    audio_model = whisper.load_model(model)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\whisper\__init__.py", line 154, in load_model
    return model.to(device)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1149, in to
    return self._apply(convert)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 801, in _apply
    module._apply(fn)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 801, in _apply
    module._apply(fn)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 801, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 824, in _apply
    param_applied = fn(param)
  File "C:\Users\laugh\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1147, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)   
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB. GPU 0 has a total capacty of 4.00 GiB of which 0 bytes is free. Of the allocated memory 3.44 GiB is allocated by PyTorch, 
and 15.11 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by davabase** [comment]
It would seem your GPU does not have enough memory to run that model. Try using a smaller model like the "tiny" one and see if that works.

**Comment by verse13** [comment]
I want to run the large model for transcriptions, may I know how much memory(RAM) and vCPU I'll be needing to get the transcription results efficiently.
