### ISSUE TITLE
Got this error when used

### ISSUE THREAD

**Issue by SamuelXGMM** [davabase/whisper_real_time#9]
➜  whisper_real_time git:(master) python3.8 transcribe_demo.py 
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "/home/samuel/.local/lib/python3.8/site-packages/speech_recognition/__init__.py", line 120, in get_pyaudio
    import pyaudio
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 116, in <module>
    import _portaudio as pa
ModuleNotFoundError: No module named '_portaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "transcribe_demo.py", line 152, in <module>
    main()
  File "transcribe_demo.py", line 58, in main
    for index, name in enumerate(sr.Microphone.list_microphone_names()):
  File "/home/samuel/.local/lib/python3.8/site-packages/speech_recognition/__init__.py", line 135, in list_microphone_names
    audio = Microphone.get_pyaudio().PyAudio()
  File "/home/samuel/.local/lib/python3.8/site-packages/speech_recognition/__init__.py", line 122, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation

**Comment by davabase** [comment]
Try installing PyAudio manually: https://pypi.org/project/PyAudio/

**Comment by mwalkerr** [comment]
On MacOS I had to `brew install portaudio` per the instructions here: https://stackoverflow.com/questions/33513522/when-installing-pyaudio-pip-cannot-find-portaudio-h-in-usr-local-include
